apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-tristan.moe-issue
    nginx.ingress.kubernetes.io/auth-url: "https://auth.tristan.moe/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.tristan.moe/oauth2/start?rd=https%3A%2F%2Fvault.tristan.moe$escaped_request_uri"
spec:
  rules:
    - host: vault.tristan.moe
      http:
        paths:
          - backend:
              serviceName: vault
              servicePort: 8200
  tls:
    - hosts:
        - vault.tristan.moe
      secretName: letsencrypt-cert-vault.tristan.moe
