apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vault-ingress
    app.kubernetes.io/part-of: vault
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: "vault.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: vault
              servicePort: 8200
  tls:
    - hosts:
        - "vault.tristan.moe"
      secretName: letsencrypt-cert-vault.tristan.moe
