apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: le-clusterissuer
spec:
  rules:
    - host: "vault.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: vault
              servicePort: 8200
  tls:
    - hosts:
        - "vault.tristan.moe"
      secretName: le-cert-vault
