apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: nexus
  name: cert-nexus-docker
spec:
  dnsNames:
    - 'docker.nexus.tristan.moe'
  issuerRef:
    kind: ClusterIssuer
    name: le-clusterissuer
  secretName: docker-nexus-tristan-moe
