apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/part-of: vpn
  name: wireguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      initContainers:
        - name: enable-sysctls
          image: busybox
          securityContext:
            privileged: true
          command: [
              'sh',
              '-c',
              '
                set -x;
                sysctl -w net.ipv4.ip_forward=1;
                sysctl -w net.ipv6.conf.all.forwarding=1
              '
          ]
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          env:
            - name: TZ
              value: "Europe/London"
            - name: SERVERURL
              value: "195.154.69.74"
            - name: SERVERPORT
              value: "30001"
            - name: PEERS
              value: "tde-pc,tde-phone,tde-misc"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
          volumeMounts:
            - name: modules
              mountPath: /lib/modules
            - name: data
              mountPath: /config
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: data
          persistentVolumeClaim:
            claimName: wireguard-pvc-ceph
