apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/part-of: vpn
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      serviceAccountName: wireguard
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          env:
            - name: TZ
              value: "Europe/London"
            - name: SERVERURL
              value: "195.154.69.74"
            - name: SERVERPORT
              value: "30001"
            - name: PEERS
              value: "tde-pc,tde-phone,tde-misc"
            - name: PEERDNS
              value: "1.1.1.1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: modules
              mountPath: /lib/modules
            - name: data
              mountPath: /config
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: modules
          hostPath:
            path: /lib/modules
        - name: data
          persistentVolumeClaim:
            claimName: wireguard-pvc
