apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
  labels:
    app.kubernetes.io/name: wireguard-pvc
    app.kubernetes.io/part-of: vpn
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 2Gi
