controller:
  kind: "DaemonSet"

  daemonset:
    useHostPort: "false"

  config:
    use-proxy-protocol: "true"
    forwardfor: "update"

  stats:
    enabled: "true"
  metrics:
    enabled: "true"
    port: "9101"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"

  service:
    type: ClusterIP
