controller:
  kind: "DaemonSet"

  daemonset:
    useHostPort: "true"

  config:
    use-proxy-protocol: "true"
    forwardfor: "update"
    limit-rps: "15"
    limit-connections: "15"

  stats:
    enabled: "true"
  metrics:
    enabled: "true"
    port: "9101"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"

  service:
    type: NodePort
