controller:
  kind: "DaemonSet"

  daemonset:
    useHostPort: "true"
    hostPorts:
      http: "80"
      https: "443"

  config:
    use-proxy-protocol: "true"
    forwardfor: "update"
    ssl-redirect: "false"

  stats:
    enabled: "true"
  metrics:
    enabled: "true"
    port: "9101"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"

  service:
    type: NodePort
