apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-ds
    app.kubernetes.io/part-of: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      name: traefik
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/part-of: traefik
    spec:
      containers:
        - name: traefik:v2.3
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 80
          env:
            - name: TRAEFIK_API
              value: "true"
            - name: TRAEFIK_API_DASHBOARD
              value: "true"

