apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-lb-service
    app.kubernetes.io/part-of: traefik
    k8s.scw.cloud/ingress: traefik2
spec:
  type: LoadBalancer
  loadBalancerIP: 195.154.69.74
  ports:
    - port: 80
      name: http
      targetPort: http
    - port: 443
      name: https
      targetPort: https
  selector:
    app.kubernetes.io/name: traefik
