apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kmdah
  name: kmdah-redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: library/redis:6-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 200Mi
