apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traefik-ingress-controller
  labels:
    app.kubernetes.io/name: traefik-ingress-controller
    app.kubernetes.io/part-of: traefik
