apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmdah
  namespace: kmdah
  labels:
    app.kubernetes.io/name: kmdah
    app.kubernetes.io/part-of: kmdah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kmdah
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kmdah
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/__mon/prometheus"
        prometheus.io/port: "8080"
        vault.hashicorp.com/role: 'kmdah'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-application-prod.yml: 'kv/mangadex/kmdah'
        vault.hashicorp.com/agent-inject-template-application-prod.yml: |
          {{- with secret "kv/mangadex/kmdah" -}}
          kmdah:
            cache:
              max-size-gb: 150
              mongodb:
                host: kmdah-mongodb-service
                port: 27017

            gossip:
              id-generation-strategy: hostname
              redis:
                host: kmdah-redis-service
                port: 6379

            k8s:
              tls-secret:
                namespace: kmdah
                name: mangadex-at-home-tls-secret

            mangadex:
              client-secret: "{{ .Data.data.mangadex_client_secret }}"

            worker:
              bandwidth-mbps: 40
          {{- end }}
    spec:
      serviceAccountName: kmdah
      containers:
        - image: tristandeloche/kmdah:0.1.1-SNAPSHOT
          imagePullPolicy: Always
          name: kmdah
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KMDAH_CONFIGURATION
              value: "/vault/secrets/application-prod.yml"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx768M"
          readinessProbe:
            httpGet:
              path: /__mon/health
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 1
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              memory: 1Gi
      terminationGracePeriodSeconds: 360
      # disallow workers to be running the same nodes, since they would be sharing bandwidth
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kmdah
