apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: codimd
spec:
  rules:
    - host: "codimd.tristan.moe"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: codimd
                port:
                  number: 80
  tls:
    - hosts:
        - "codimd.tristan.moe"
      secretName: wildcard-tristan-moe
