apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: codimd-pgsql
spec:
  storageClassName: csi-rbd-sc
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 20Gi
