apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3ql-master
  labels:
    app.kubernetes.io/name: s3ql-master
    app.kubernetes.io/part-of: media
spec:
  selector:
    matchLabels:
      app: s3ql-master
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s3ql-master
      annotations:
        vault.hashicorp.com/role: 's3ql-master'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-scaleway-credentials: 'kv/scaleway/s3ql-master/authinfo'
        vault.hashicorp.com/agent-inject-template-scaleway-credentials: |
          {{- with secret "kv/scaleway/s3ql-master/authinfo" -}}
          [s3c]
          storage-url: {{ .Data.data.SCW_STORAGE_URL }}
          backend-login: {{ .Data.data.SCW_ACCESS_KEY_ID }}
          backend-password: {{ .Data.data.SCW_SECRET_ACCESS_KEY }}
          {{- end }}
    spec:
      serviceAccountName: s3ql-master
      terminationGracePeriodSeconds: 600
      containers:
        - name: s3ql
          imagePullPolicy: Always
          image: rg.fr-par.scw.cloud/tristandeloche/s3ql:131-container-friendliness-3
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 1500m
              memory: 2000Mi
            limits:
              cpu: 1500m
              memory: 2000Mi
          env:
            - name: S3QL_STORAGE_URL
              value: "s3c://s3.fr-par.scw.cloud/s3ql-seed"
            - name: S3QL_MOUNTPOINT
              value: "/s3-data/data"
            - name: S3QL_AUTHFILE
              value: "/vault/secrets/scaleway-credentials"
            - name: S3QL_CACHEDIR
              value: "/s3-cache"
            - name: S3QL_CACHESIZE
              value: "26214400"
            - name: S3QL_COMPRESS
              value: "none"
            - name: S3QL_FS_NAME
              value: "s3ql-seed"
            - name: S3QL_THREADS
              value: "2"
            - name: S3QL_KEEP_CACHE
              value: "false"
            - name: S3QL_ALLOW_OTHER
              value: "true"
            - name: S3QL_NFS
              value: "true"
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: s3ql-cache
              mountPath: /s3-cache
            - name: s3-data
              mountPath: /s3-data
              mountPropagation: Bidirectional
        - name: nfs-server
          imagePullPolicy: Always
          image: tristandeloche/nfs-ganesha:master
          env:
            - name: 'EXPORT_PATH'
              value: '/nfs/data'
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 2049
          volumeMounts:
            - mountPath: /nfs
              name: s3-data
              mountPropagation: HostToContainer
      volumes:
        # fuse device to use for mounting the s3ql filesystem
        - name: devfuse
          hostPath:
            path: /dev/fuse
        # shared volume to which the NFS server writes (due to other nodes using the NFS server)
        - name: s3-data
          emptyDir: { }
        - name: s3ql-cache
          persistentVolumeClaim:
            claimName: s3ql-cache
