apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3ql-master
  labels:
    app.kubernetes.io/name: s3ql-master
    app.kubernetes.io/part-of: media
spec:
  selector:
    matchLabels:
      app: s3ql-master
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s3ql-master
      annotations:
        vault.hashicorp.com/role: 's3ql-master'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-scaleway-credentials: 'kv/scaleway/s3ql-master/authinfo'
        vault.hashicorp.com/agent-inject-template-scaleway-credentials: |
          {{- with secret "kv/scaleway/s3ql-master/authinfo" -}}
          [s3c]
          storage-url: {{ .Data.data.SCW_STORAGE_URL }}
          backend-login: {{ .Data.data.SCW_ACCESS_KEY_ID }}
          backend-password: {{ .Data.data.SCW_SECRET_ACCESS_KEY }}
          {{- end }}
    spec:
      serviceAccountName: s3ql-master
      terminationGracePeriodSeconds: 600
      containers:
        - name: s3ql
          imagePullPolicy: Always
          image: tristandeloche/s3ql-docker:191-container-friendliness
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 750m
              memory: 768Mi
            limits:
              cpu: 1750m
              memory: 1795Mi
          env:
            - name: STORAGE_URL
              value: s3c://s3.fr-par.scw.cloud/s3ql-seed
            - name: MOUNT_POINT
              value: /s3-data/data
            - name: AUTH_FILE
              value: /vault/secrets/scaleway-credentials
            - name: LOG_FILE
              value: /s3ql/logs/s3ql.log
            - name: CACHE_DIR
              value: /s3-cache
            - name: CACHE_SIZE
              value: "26214400"
            - name: COMPRESS
              value: none
            - name: FS_NAME
              value: s3ql-seed
            - name: UPLOAD_THREADS
              value: "2"
            - name: KEEP_CACHE
              value: "false"
            - name: ALLOW_OTHER
              value: "true"
            - name: NFS
              value: "true"
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: s3ql-cache
              mountPath: /s3-cache
            - name: s3-data
              mountPath: /s3-data:shared
        - name: nfs-server
          imagePullPolicy: Always
          image: tristandeloche/nfs-ganesha:master
          env:
            - name: 'EXPORT_PATH'
              value: '/nfs/data'
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          ports:
            - containerPort: 2049
          volumeMounts:
            # /path/to/share:/nfs
            - mountPath: /nfs:shared
              name: s3-data
      volumes:
        # fuse device to use for mounting the s3ql filesystem
        - name: devfuse
          hostPath:
            path: /dev/fuse
        # shared volume to which the NFS server writes (due to other nodes using the NFS server)
        - name: s3-data
          hostPath:
            path: /mnt/s3-data
        - name: s3ql-cache
          persistentVolumeClaim:
            claimName: s3ql-cache-ceph
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: mangadex-at-home
