apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: default
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.233.0.100
    path: "/"
  mountOptions:
    - noacl
    - nocto
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
