apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  volumeName: nfs-pv
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
