apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seed
  namespace: default
spec:
  rules:
    - host: "seed.tristan.moe"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: seed-rtorrent-flood
                port:
                  number: 3000
  tls:
    - hosts:
        - "seed.tristan.moe"
      secretName: wildcard-tristan-moe
