apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: seed-ingress
  labels:
    app.kubernetes.io/name: seed-ingress
    app.kubernetes.io/part-of: seed
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`seed.tristan.moe`)
      kind: Rule
      services:
        - name: seed
          port: 3000
      middlewares:
        - name: oauth-middleware
          namespace: default
  tls:
    secretName: letsencrypt-cert-seed.tristan.moe
