apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kmdah
  name: kmdah-mongodb
  labels:
    app.kubernetes.io/name: kmdah-mongodb
    app.kubernetes.io/part-of: kmdah
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kmdah-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kmdah-mongodb
    spec:
      containers:
        - name: mongodb
          image: library/mongo:4.4
          args:
            - --dbpath
            - /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "kmdah"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "kmdah"
          ports:
            - containerPort: 27017
              name: mongodb
              hostPort: 27017
          volumeMounts:
            - name: kmdah-mongodb-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 2000m
              memory: 2500Mi
            limits:
              memory: 2500Mi
      volumes:
        - name: kmdah-mongodb-data
          persistentVolumeClaim:
            claimName: kmdah-mongodb-pvc
