apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: kmdah
  name: kmdah-mongos
  labels:
    app.kubernetes.io/name: kmdah-mongos
    app.kubernetes.io/part-of: kmdah

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kmdah-mongos
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kmdah-mongos
    spec:
      containers:
        - name: mongodb
          image: library/mongo:4.4
          command:
            - /usr/bin/mongos
          args:
            - --config
            - /config/mongos.yml
          ports:
            - containerPort: 27017
              name: mongos
              hostPort: 27017
          volumeMounts:
            - name: mongos-config
              mountPath: /config
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 512Mi
      volumes:
        - name: mongos-config
          configMap:
            name: kmdah-mongos-config
            items:
              - key: mongos.yml
                path: mongos.yml
