apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kmdah
  name: kmdah-mongod-configsvr-pvc
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
