apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kmdah
  name: kmdah-mongodb-prom-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kmdah-mongodb-prom-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kmdah-mongodb-prom-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "metrics"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: mongodb-exporter
          image: ssheehy/mongodb-exporter:0.11.0
          env:
            - name: MONGODB_URI
              value: "mongodb://kmdah-mongos:27017"
          ports:
            - containerPort: 9216
              name: metrics
              hostPort: 9216
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 10
