apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmdah
  namespace: kmdah
  labels:
    app.kubernetes.io/name: kmdah
    app.kubernetes.io/part-of: kmdah
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kmdah
  template:
    metadata:
      labels:
        app: kmdah
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        vault.hashicorp.com/role: 'kmdah'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-application-prod.yml: 'kv/mangadex/kmdah'
        vault.hashicorp.com/agent-inject-template-application-prod.yml: |
          {{- with secret "kv/mangadex/kmdah" -}}
          # avoid creating and destroying threads all the time
          # and use a constant pool
          server.jetty.threads:
            min: 100
            max: 500

          spring.data.mongodb:
            database: kmdah
            gridfs:
              database: kmdah

          kmdah:
            cache:
              backend: mongodb
              max-size-gb: 1500
              mongodb:
                host: kmdah-mongodb
                port: 27017
                username: {{ .Data.data.mongodb_username }}
                password: {{ .Data.data.mongodb_password }}

            geoip:
              enabled: true
              license-key: "{{ .Data.data.maxmind_license_key }}"

            gossip:
              id-generation-strategy: hostname
              redis:
                host: kmdah-redis-service
                port: 6379

            tls:
              backend: k8s
              k8s:
                secret:
                  auto-update: true
                  namespace: kmdah
                  name: mangadex-at-home-tls-secret

            mangadex:
              client-secret: "{{ .Data.data.mangadex_client_secret }}"
              load-balancer-ip: "124.6.36.229"
              bandwidth-mbps: 2000
          {{- end }}
    spec:
      serviceAccountName: kmdah
      containers:
        - image: rg.fr-par.scw.cloud/tristandeloche/kmdah:0.3.34
          imagePullPolicy: Always
          name: kmdah
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KMDAH_CONFIGURATION
              value: "/vault/secrets/application-prod.yml"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms512M -Xmx512M -Xss512K -XX:+UseShenandoahGC"
          readinessProbe:
            httpGet:
              path: /__mon/health
              port: http
            periodSeconds: 5
            timeoutSeconds: 10
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 1
          resources:
            requests:
              cpu: 500m
              memory: 2000Mi
            limits:
              memory: 2000Mi
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "10" ] # give 10s to traefik to remove the pod from all nodes' Endpoints
      terminationGracePeriodSeconds: 360
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kmdah
