apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmdah
  namespace: kmdah
  labels:
    app.kubernetes.io/name: kmdah
    app.kubernetes.io/part-of: kmdah
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kmdah
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kmdah
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        vault.hashicorp.com/role: 'kmdah'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-application-prod.yml: 'kv/mangadex/kmdah'
        vault.hashicorp.com/agent-inject-template-application-prod.yml: |
          {{- with secret "kv/mangadex/kmdah" -}}
          kmdah:
            cache:
              backend: mongodb
              max-size-gb: 420
              mongodb:
                host: {{ .Data.data.mongodb_host }}
                port: {{ .Data.data.mongodb_port }}
                username: {{ .Data.data.mongodb_username }}
                password: {{ .Data.data.mongodb_password }}

            geoip:
              enabled: true
              license-key: "{{ .Data.data.maxmind_license_key }}"

            gossip:
              id-generation-strategy: hostname
              redis:
                host: {{ .Data.data.redis_host }}
                port: {{ .Data.data.redis_port }}

            k8s:
              tls-secret:
                auto-update: true
                namespace: kmdah
                name: mangadex-at-home-tls-secret

            mangadex:
              client-secret: "{{ .Data.data.mangadex_client_secret }}"
              load-balancer-ip: "195.154.69.74"

            worker:
              bandwidth-mbps: 400
          {{- end }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 169.254.20.69
          - 10.32.0.10
        searches:
          - kmdah.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: "ndots"
            value: "5"
      serviceAccountName: kmdah
      containers:
        - image: tristandeloche/kmdah:0.3.18-SNAPSHOT
          imagePullPolicy: Always
          name: kmdah
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: kmdah-data
              mountPath: "/var/lib/kmdah"
          env:
            - name: KMDAH_CONFIGURATION
              value: "/vault/secrets/application-prod.yml"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512M"
          readinessProbe:
            httpGet:
              path: /__mon/health
              port: http
            periodSeconds: 5
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 1
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              memory: 768Mi
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "10" ] # give 10s to traefik to remove the pod from all nodes' Endpoints
      terminationGracePeriodSeconds: 360
      volumes:
        - name: kmdah-data
          persistentVolumeClaim:
            claimName: kmdah-pvc
      # disallow workers to be running the same nodes, since they would be sharing bandwidth
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kmdah
