apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kmdah-ingress-production
  namespace: kmdah
  annotations:
    ingress.kubernetes.io/limit-rps: "150"
    ingress.kubernetes.io/limit-connections: "150"
    ingress.kubernetes.io/config-backend: |
      http-request deny if { path -i -m beg /__ }
spec:
  rules:
    - host: "*.rmhkd98sb0x3y.mangadex.network"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kmdah-service
                port:
                  name: http
  tls:
    - hosts:
        - "*.rmhkd98sb0x3y.mangadex.network"
      secretName: mangadex-at-home-tls-secret
