apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmdah-role
  namespace: kmdah
  labels:
    app.kubernetes.io/name: kmdah-role
    app.kubernetes.io/part-of: kmdah

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - mangadex-at-home-tls-secret
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmdah-rolebinding
  namespace: kmdah
  labels:
    app.kubernetes.io/name: kmdah-rolebinding
    app.kubernetes.io/part-of: kmdah

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmdah-role
subjects:
  - kind: ServiceAccount
    name: kmdah
    namespace: kmdah
