apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kmdah
  name: kmdah-mongodb-config
data:
  config.yml: |
    systemLog:
      timeStampFormat: iso8601-utc

    net:
      bindIpAll: true
      tls:
        mode: disabled

    security:
      authorization: disabled

    storage:
      dbPath: /data/db
