apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ns3
  name: ns3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns3
  template:
    metadata:
      labels:
        app: ns3
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.3
          name: ns3
          env:
            - name: DISABLE_AUTH
              value: "true"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/share"
          resources:
            requests:
              cpu: 0m
              memory: 70Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
