apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ns3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ns3
  template:
    metadata:
      labels:
        app: ns3
    spec:
      containers:
        - image: fraoustin/fancyindex
          name: ns3
          env:
            - name: DISABLE_AUTH
              value: "true"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nfs
              mountPath: "/share"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: phys_host
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ns3
