apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ns3
  name: ns3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns3
  template:
    metadata:
      labels:
        app: ns3
    spec:
      containers:
        - image: nginx:stable
          name: ns3
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
