apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ns3-ingress
  labels:
    app.kubernetes.io/name: ns3-ingress
    app.kubernetes.io/part-of: ns3
  annotations:
    kubernetes.io/ingress.class: haproxy
    #ingress.kubernetes.io/oauth: oauth2_proxy
spec:
  rules:
    - host: "ns3.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: ns3
              servicePort: 8080
          - path: /oauth2
            backend:
              serviceName: oauth2-proxy
              servicePort: 4180
  tls:
    - hosts:
        - "ns3.tristan.moe"
      secretName: letsencrypt-cert-ns3.tristan.moe
