apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ns3-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-tristan.moe-issue
spec:
  rules:
    - host: ns3.k8s.tristan.moe
      http:
        paths:
          - backend:
              serviceName: ns3
              servicePort: 80
  tls:
    - hosts:
        - ns3.k8s.tristan.moe
      secretName: letsencrypt-cert-ns3.k8s.tristan.moe
