apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ns3-ingress
  labels:
    app.kubernetes.io/name: ns3-ingress
    app.kubernetes.io/part-of: ns3
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ns3.tristan.moe`)
      kind: Rule
      services:
        - name: ns3
          port: 80
      middlewares:
        - name: oauth-middleware
          namespace: default
  tls:
    secretName: letsencrypt-cert-ns3.tristan.moe
