apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ns3-ingress
  labels:
    app.kubernetes.io/name: ns3-ingress
    app.kubernetes.io/part-of: ns3
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: le-clusterissuer
spec:
  rules:
    - host: "ns3.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: ns3
              servicePort: 8080
  tls:
    - hosts:
        - "ns3.tristan.moe"
      secretName: le-cert-ns3
