apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb
data:
  config: |
    peers:
    - peer-address: 172.17.38.1
      peer-asn: 24482
      my-asn: 65000
      hold-time: 120s
      node-selectors:
      - match-labels:
          node_role: worker

    address-pools:
    - name: ip-144
      protocol: bgp
      addresses:
      - 124.6.37.144/32
      auto-assign: false
