apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: itzg/minecraft-server:adopt13
          name: minecraft
          env:
            - name: TYPE
              value: "FORGE"
            - name: EULA
              value: "true"
            - name: RCON_PORT
              value: "25575"
            - name: RCON_PASSWORD
              value: "rcon"
            - name: WHITELIST
              value: "tristan971,whixR"
            - name: OPS
              value: "tristan971,whixR"
            - name: MOTD
              value: "Walecraft"
            - name: LEVEL_TYPE
              value: "AMPLIFIED"
            - name: UID
              value: "0"
            - name: GID
              value: "0"
            - name: MEMORY
              value: "768M"
          ports:
            - containerPort: 25565
            - containerPort: 25575
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
