apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: netdata-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-tristan.moe-issue
spec:
  rules:
    - host: netdata.tristan.moe
      http:
        paths:
          - backend:
              serviceName: netdata
              servicePort: 19999
  tls:
    - hosts:
        - netdata.tristan.moe
      secretName: letsencrypt-cert-netdata.tristan.moe
