apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: kmdah-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.10"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: kmdah
      db: kmdah
      passwordSecretRef:
        name: kmdah-mongodb-user-password
        key: password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: kmdah-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 1000m
                  memory: 1Gi
                limits:
                  cpu: 1000m
                  memory: 1Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 300m
                  memory: 384Mi
                limits:
                  cpu: 300m
                  memory: 384Mi
          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                resources:
                  requests:
                    storage: 100Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:
              requests:
                storage: 100Gi
