apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmdah-operator
  labels:
    app.kubernetes.io/name: kmdah-operator
    app.kubernetes.io/part-of: kmdah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmdah-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kmdah-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/__mon/prometheus"
        prometheus.io/port: "8080"
        vault.hashicorp.com/role: 'kmdah'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-application-prod.yml: 'kv/mangadex/kmdah'
        vault.hashicorp.com/agent-inject-template-application-prod.yml: |
          {{- with secret "kv/mangadex/kmdah" -}}
          kmdah:
            mangadex:
              client-secret: "{{ .Data.data.mangadex_client_secret }}"
              graceful-shutdown-seconds: 300

            operator:
              port: 8080
              redirect-uri: "https://mdah.tristan.moe"

            tls-secret:
              namespace: "default"
              name: "mangadex-at-home-tls-secret"

            cache:
              max-size-gb: 150

            s3:
              service-uri: "{{ .Data.data.bucket_endpoint }}"
              signing-region: "{{ .Data.data.bucket_region }}"
              access-key-id: "{{ .Data.data.aws_access_key_id }}"
              secret-access-key: "{{ .Data.data.aws_secret_access_key }}"
              bucket-name: "{{ .Data.data.bucket_name }}"
          {{- end }}
    spec:
      serviceAccountName: kmdah
      containers:
        - image: tristandeloche/kmdah-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: kmdah-operator
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KMDAH_CONFIG_DIR
              value: "/vault/secrets/"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseShenandoahGC -Xms256M -Xmx512M"
          resources:
            requests:
              cpu: 1000m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 768Mi
      terminationGracePeriodSeconds: 350
