apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: logs
  labels:
    app.kubernetes.io/name: prometheus-ingress
    app.kubernetes.io/part-of: prometheus
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: le-clusterissuer
spec:
  rules:
    - host: "prom.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: prometheus-server
              servicePort: 80
  tls:
    - hosts:
        - "prom.tristan.moe"
      secretName: le-cert-prometheus
