server:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.27.1
  persistentVolume:
    enabled: true
    existingClaim: prometheus
  retention: 30d

  resources:
    requests:
      cpu: 1500m
      memory: 2Gi
    limits:
      memory: 2Gi

nodeExporter:
  enabled: true
  image:
    repository: prom/node-exporter
    tag: v1.1.2

alertmanager:
  enabled: false
pushgateway:
  enabled: false
