server:
  enabled: true

  image:
    repository: docker.tristan.moe/prom/prometheus
    tag: v2.27.1

  strategy:
    type: Recreate

  persistentVolume:
    enabled: true
    existingClaim: prometheus
  retention: 30d

  resources:
    requests:
      cpu: 1500m
      memory: 2Gi
    limits:
      memory: 2Gi

nodeExporter:
  enabled: true
  image:
    repository: docker.tristan.moe/prom/node-exporter
    tag: v1.1.2
  service:
    listenOnAllInterfaces: false
  hostNetwork: false

alertmanager:
  enabled: false
pushgateway:
  enabled: false
