apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site
  name: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: nginx-site
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site-workdir
              mountPath: /usr/share/nginx
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: git-sync-site
          image: k8s.gcr.io/git-sync:v3.1.6
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          env:
            - name: 'GIT_SYNC_REPO'
              value: 'https://github.com/Tristan971/tristan.moe.git'
            - name: 'GIT_SYNC_ROOT'
              value: '/tmp/site-repo'
            - name: 'GIT_SYNC_DEST'
              value: 'html'
            - name: 'GIT_SYNC_WAIT'
              value: '300' # sync every 5 minutes
            - name: 'GIT_SYNC_PERMISSIONS'
              value: '493' # = 755 in non-stupid notation
          volumeMounts:
            - name: site-workdir
              mountPath: /tmp/site-repo
          resources:
            requests:
              cpu: 10m
              memory: 35Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: site-workdir
          emptyDir:
            sizeLimit: 1Gi
