apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  strategy: { }
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - image: nginx:stable
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
