apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: site-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: site-ingress
    app.kubernetes.io/part-of: site
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: "tristan.moe"
      http:
        paths:
          - backend:
              serviceName: site
              servicePort: 80
  tls:
    - hosts:
        - "tristan.moe"
        - "trde9.com"
      secretName: letsencrypt-cert-site.tristan.moe
