apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: site-ingress
  labels:
    app.kubernetes.io/name: site-ingress
    app.kubernetes.io/part-of: site
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`tristan.moe`) || Host(`trde9.com`)
      kind: Rule
      services:
        - name: site
          port: 80
      middlewares:
        - name: http-to-https-middleware
          namespace: kube-system
  tls:
    secretName: letsencrypt-cert-site.tristan.moe
