apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/part-of: unifi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - image: linuxserver/unifi-controller
          name: unifi-controller
          env:
            - name: MEM_LIMIT
              value: "512M"
          ports:
            # overriden ports in system.properties
            # to make generated URLs/redirects coherent
            # yes the port requirements are horrible
            - name: comms
              containerPort: 31501
              protocol: TCP
            - name: web
              containerPort: 31502
              protocol: TCP
            - name: stun
              containerPort: 31503
              protocol: UDP
          volumeMounts:
            - name: unifi-data
              mountPath: /config
          resources:
            requests:
              cpu: 800m
              memory: 768Mi
            limits:
              cpu: 800m
              memory: 768Mi
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-pvc
