apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc-ceph
  labels:
    app.kubernetes.io/name: unifi-pvc-ceph
    app.kubernetes.io/part-of: unifi
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: rook-ceph-block-default
  resources:
    requests:
      storage: 10Gi
