apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
  labels:
    app.kubernetes.io/part-of: unifi
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 32Gi
