apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-config
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "oauth"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = <<EOH
          {{- with secret "kv/oauth/secrets" -}}
          ## Are we running behind a reverse proxy? Will not accept headers like X-Real-Ip unless this is set.
          reverse_proxy = true

          ## OAuth provider setup
          provider = "github"
          client_id = "{{ .Data.data.GH_APP_CLIENT_ID }}"
          client_secret = "{{ .Data.data.GH_APP_CLIENT_SECRET }}"
          github_users = [
            "Tristan971"
          ]

          ## Pass OAuth Access token to upstream via "X-Forwarded-Access-Token"
          pass_access_token = false

          ## Cookie Settings
          ## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
          cookie_secret = "{{ .Data.data.COOKIE_SECRET }}"
          {{- end }}
      EOH
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "https://vault.kube-system.svc.cluster.local:8200"
    }


  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "oauth"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = <<EOH
          {{- with secret "kv/oauth/secrets" -}}
          ## Are we running behind a reverse proxy? Will not accept headers like X-Real-Ip unless this is set.
          reverse_proxy = true

          ## OAuth provider setup
          provider = "github"
          client_id = "{{ .Data.data.GH_APP_CLIENT_ID }}"
          client_secret = "{{ .Data.data.GH_APP_CLIENT_SECRET }}"
          github_users = [
          "Tristan971"
          ]

          ## Pass OAuth Access token to upstream via "X-Forwarded-Access-Token"
          pass_access_token = false

          ## Cookie Settings
          ## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
          cookie_secret = "{{ .Data.data.COOKIE_SECRET }}"
          {{- end }}
      EOH
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "https://vault.kube-system.svc.cluster.local:8200"
    }
