apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-tristan.moe-issue
spec:
  rules:
    - host: auth.tristan.moe
      http:
        paths:
          - backend:
              serviceName: oauth
              servicePort: web
  tls:
    - hosts:
        - auth.tristan.moe
      secretName: letsencrypt-cert-oauth.tristan.moe
