apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth-ingress
  labels:
    app.kubernetes.io/name: oauth-ingress
    app.kubernetes.io/part-of: oauth
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: "ns3.tristan.moe"
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 4180
            path: /oauth2
  tls:
    - hosts:
        - "ns3.tristan.moe"
      secretName: letsencrypt-cert-oauth.tristan.moe
