apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth-ingress
  labels:
    app.kubernetes.io/name: oauth-ingress
    app.kubernetes.io/part-of: oauth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.tristan.moe`)
      kind: Rule
      services:
        - name: oauth
          port: 4180
  tls:
    secretName: letsencrypt-cert-oauth.tristan.moe
