# Oauth client configuration specifics
config:
  configFile: oauth-config

## Use ServiceAccount with Vault access
serviceAccount:
  name: oauth

# whether to use http or https
httpScheme: http

podAnnotations:
  vault.hashicorp.com/role: "oauth"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-configmap: "oauth-config"
