apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv
  namespace: default
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.tcp.s3ql-master-nfs.object-storage.svc.cluster.local
    path: "/"
