apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: le-clusterissuer
spec:
  acme:
    email: "tde@hey.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-privkey
    solvers:
      - http01:
          ingress:
            class: haproxy
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
            config:
              accessKeySecretRef:
                key: SCW_ACCESS_KEY
                name: scaleway-secret
              secretKeySecretRef:
                key: SCW_SECRET_KEY
                name: scaleway-secret
