apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: le-clusterissuer
spec:
  acme:
    email: "tde@hey.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-privkey
    solvers:
      - http01:
          ingress:
            class: haproxy
