apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-plex
  labels:
    app.kubernetes.io/name: cert-plex
    app.kubernetes.io/part-of: plex
spec:
  commonName: plex.tristan.moe
  secretName: letsencrypt-cert-plex.tristan.moe
  dnsNames:
    - plex.tristan.moe
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-tristan.moe-issue
