apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: default
spec:
  volumeName: plex-config
  resources:
    requests:
      storage: 10Gi
  accessModes: [ ReadWriteOnce ]
