apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          ports:
            - containerPort: 32400
              name: webui
          env:
            # we need to set plex user uid/gid so that
            # additional plugins can safely, acl-wise
            # be updated within its config files from
            # another container
            - name: 'PLEX_UID'
              value: '1000'
            - name: 'PLEX_GID'
              value: '1000'
          volumeMounts:
            - name: plex-config
              mountPath: /config:shared
            - name: nfs-plex-data
              mountPath: /data
      volumes:
        - name: nfs-plex-data
          persistentVolumeClaim:
            claimName: nfs-pvc
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
