apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
    app.kubernetes.io/name: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 32400
              name: webui
          env:
            # we need to set plex user uid/gid so that
            # additional plugins can safely, acl-wise
            # be updated within its config files from
            # another container
            - name: 'PLEX_UID'
              value: '0'
            - name: 'PLEX_GID'
              value: '0'
          volumeMounts:
            - name: plex-config
              mountPath: /config
              mountPropagation: HostToContainer
            - name: nfs-plex-data
              mountPath: /data
          resources:
            requests:
              cpu: 250m
              memory: 1570Mi
            limits:
              cpu: 1000m
              memory: 1570Mi
        - name: git-sync-hama-bundle
          image: k8s.gcr.io/git-sync:v3.1.6
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          env:
            - name: 'GIT_SYNC_REPO'
              value: 'https://github.com/ZeroQI/Hama.bundle.git'
            - name: 'GIT_SYNC_ROOT'
              value: '/tmp/plex-config/git-sync/hama-bundle/workdir'
            - name: 'GIT_SYNC_DEST'
              value: 'latest'
            - name: 'GIT_SYNC_WAIT'
              value: '86400' # 24h
            - name: 'GIT_SYNC_PERMISSIONS'
              value: '493' # equiv to 0755 cause impressible stupid choice of base
          volumeMounts:
            - name: plex-config
              mountPath: /tmp/plex-config
              mountPropagation: HostToContainer
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 64Mi
        - name: git-sync-ass
          image: k8s.gcr.io/git-sync:v3.1.6
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          env:
            - name: 'GIT_SYNC_REPO'
              value: 'https://github.com/ZeroQI/Absolute-Series-Scanner.git'
            - name: 'GIT_SYNC_ROOT'
              value: '/tmp/plex-config/git-sync/ass/workdir'
            - name: 'GIT_SYNC_DEST'
              value: 'latest'
            - name: 'GIT_SYNC_WAIT'
              value: '86400' # 24h
            - name: 'GIT_SYNC_PERMISSIONS'
              value: '493' # equiv to 0755 cause impressively stupid choice of base
          volumeMounts:
            - name: plex-config
              mountPath: /tmp/plex-config
              mountPropagation: HostToContainer
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: nfs-plex-data
          persistentVolumeClaim:
            claimName: nfs-pvc
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config-pvc
