apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
    - host: "plex.tristan.moe"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts:
        - "plex.tristan.moe"
      secretName: wildcard-tristan-moe
