apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plex-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-tristan.moe-issue
spec:
  rules:
    - host: plex.tristan.moe
      http:
        paths:
          - backend:
              serviceName: plex
              servicePort: webui
  tls:
    - hosts:
        - plex.tristan.moe
      secretName: letsencrypt-cert-plex.tristan.moe
