apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-ceph
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: rook-ceph-block-default
  resources:
    requests:
      storage: 15Gi
