apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  labels:
    app.kubernetes.io/name: plex-config-pvc
    app.kubernetes.io/part-of: media
spec:
  storageClassName: csi-rbd-sc
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 20Gi
